/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Seo = {
  _type: "seo";
  title?: string;
  description?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type ExampleSlice = {
  _type: "exampleSlice";
  eyebrow?: string;
  heading?: string;
  body?: string;
  tone?: "default" | "muted";
  padding_top?:
    "none" | "240" | "200" | "160" | "128" | "104" | "80" | "64" | "40";
  padding_bottom?:
    "none" | "240" | "200" | "160" | "128" | "104" | "80" | "64" | "40";
};

export type PageBuilder = Array<
  {
    _key: string;
  } & ExampleSlice
>;

export type Page = {
  _id: string;
  _type: "page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  modules?: PageBuilder;
  seo?: Seo;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type HomePage = {
  _id: string;
  _type: "homePage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  modules?: PageBuilder;
  seo?: Seo;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type MuxVideoAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "mux.videoAsset";
};

export type MuxVideo = {
  _type: "mux.video";
  asset?: MuxVideoAssetReference;
};

export type MuxVideoAsset = {
  _id: string;
  _type: "mux.videoAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  status?: string;
  assetId?: string;
  playbackId?: string;
  filename?: string;
  thumbTime?: number;
  data?: MuxAssetData;
};

export type MuxAssetData = {
  _type: "mux.assetData";
  resolution_tier?: string;
  upload_id?: string;
  created_at?: string;
  id?: string;
  status?: string;
  max_stored_resolution?: string;
  passthrough?: string;
  encoding_tier?: string;
  video_quality?: string;
  master_access?: string;
  aspect_ratio?: string;
  duration?: number;
  max_stored_frame_rate?: number;
  mp4_support?: string;
  max_resolution_tier?: string;
  tracks?: Array<
    {
      _key: string;
    } & MuxTrack
  >;
  playback_ids?: Array<
    {
      _key: string;
    } & MuxPlaybackId
  >;
  static_renditions?: MuxStaticRenditions;
  master?: MuxMasterFile;
};

export type MuxMasterFile = {
  _type: "mux.masterFile";
  status?: string;
  url?: string;
};

export type MuxStaticRenditions = {
  _type: "mux.staticRenditions";
  status?: string;
  files?: Array<
    {
      _key: string;
    } & MuxStaticRenditionFile
  >;
};

export type MuxStaticRenditionFile = {
  _type: "mux.staticRenditionFile";
  name?: string;
  ext?: string;
  height?: number;
  width?: number;
  bitrate?: number;
  filesize?: string;
  type?: string;
  status?: string;
  resolution_tier?: string;
  resolution?: string;
  id?: string;
  passthrough?: string;
};

export type MuxPlaybackId = {
  _type: "mux.playbackId";
  id?: string;
  policy?: string;
};

export type MuxTrack = {
  _type: "mux.track";
  id?: string;
  type?: string;
  max_width?: number;
  max_frame_rate?: number;
  duration?: number;
  max_height?: number;
  language_code?: string;
  name?: string;
  status?: string;
  text_source?: string;
  text_type?: string;
};

export type MediaTag = {
  _id: string;
  _type: "media.tag";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: Slug;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | Seo
  | ExampleSlice
  | PageBuilder
  | Page
  | Slug
  | HomePage
  | SanityImageCrop
  | SanityImageHotspot
  | MuxVideoAssetReference
  | MuxVideo
  | MuxVideoAsset
  | MuxAssetData
  | MuxMasterFile
  | MuxStaticRenditions
  | MuxStaticRenditionFile
  | MuxPlaybackId
  | MuxTrack
  | MediaTag
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: ../site/app/sanity/queries/pages/home.ts
// Variable: HOME_PAGE_QUERY
// Query: *[_type == "homePage"][0]{    _id,    title,    modules[_type == "exampleSlice"]{    _type == 'exampleSlice' => {    _type,    _key,    eyebrow,    heading,    body,    tone,      padding_top,  padding_bottom  },  _type,  _key},    seo  }
export type HOME_PAGE_QUERY_RESULT = {
  _id: string;
  title: string | null;
  modules: Array<{
    _type: "exampleSlice";
    _key: string;
    eyebrow: string | null;
    heading: string | null;
    body: string | null;
    tone: "default" | "muted" | null;
    padding_top:
      | "104"
      | "128"
      | "160"
      | "200"
      | "240"
      | "40"
      | "64"
      | "80"
      | "none"
      | null;
    padding_bottom:
      | "104"
      | "128"
      | "160"
      | "200"
      | "240"
      | "40"
      | "64"
      | "80"
      | "none"
      | null;
  }> | null;
  seo: Seo | null;
} | null;

// Source: ../site/app/sanity/queries/pages/standardPage.ts
// Variable: PAGE_QUERY
// Query: *[_type == "page" && slug.current == $slug][0]{    _id,    _type,    title,    slug,    modules[_type == "exampleSlice"]{    _type == 'exampleSlice' => {    _type,    _key,    eyebrow,    heading,    body,    tone,      padding_top,  padding_bottom  },  _type,  _key},    seo  }
export type PAGE_QUERY_RESULT = {
  _id: string;
  _type: "page";
  title: string | null;
  slug: Slug | null;
  modules: Array<{
    _type: "exampleSlice";
    _key: string;
    eyebrow: string | null;
    heading: string | null;
    body: string | null;
    tone: "default" | "muted" | null;
    padding_top:
      | "104"
      | "128"
      | "160"
      | "200"
      | "240"
      | "40"
      | "64"
      | "80"
      | "none"
      | null;
    padding_bottom:
      | "104"
      | "128"
      | "160"
      | "200"
      | "240"
      | "40"
      | "64"
      | "80"
      | "none"
      | null;
  }> | null;
  seo: Seo | null;
} | null;

// Source: ../site/app/sanity/queries/pages/standardPage.ts
// Variable: PAGE_SLUGS_QUERY
// Query: *[_type == "page" && defined(slug.current)][].slug.current
export type PAGE_SLUGS_QUERY_RESULT = Array<string | null>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_type == "homePage"][0]{\n    _id,\n    title,\n    modules[_type == "exampleSlice"]{\n  \n  _type == \'exampleSlice\' => {\n    _type,\n    _key,\n    eyebrow,\n    heading,\n    body,\n    tone,\n    \n  padding_top,\n  padding_bottom\n\n  }\n,\n  _type,\n  _key\n},\n    seo\n  }\n': HOME_PAGE_QUERY_RESULT;
    '\n  *[_type == "page" && slug.current == $slug][0]{\n    _id,\n    _type,\n    title,\n    slug,\n    modules[_type == "exampleSlice"]{\n  \n  _type == \'exampleSlice\' => {\n    _type,\n    _key,\n    eyebrow,\n    heading,\n    body,\n    tone,\n    \n  padding_top,\n  padding_bottom\n\n  }\n,\n  _type,\n  _key\n},\n    seo\n  }\n': PAGE_QUERY_RESULT;
    '\n  *[_type == "page" && defined(slug.current)][].slug.current\n': PAGE_SLUGS_QUERY_RESULT;
  }
}
